"use client";

import React from "react";
import Link from "next/link";
import { Heading, Paragraph, Card } from "@leapmoney/ui";
import {
  FileText,
  Download,
  RefreshCw,
  ChevronRight,
  CheckCircle,
  TrendingUp,
  TrendingDown,
  Minus,
} from "lucide-react";

interface ReportEntry {
  id: string;
  pan: string;
  name: string;
  fetchedAt: string;
  leapScore: number;
  cibil: number;
  experian: number;
  crif: number;
  equifax: number;
  trend: "up" | "down" | "same";
  trendPts: number;
}

const MOCK_REPORTS: ReportEntry[] = [
  {
    id: "RPT-20260620",
    pan: "AWPPM4863Q",
    name: "Demo User",
    fetchedAt: "2026-06-20T10:30:00.000Z",
    leapScore: 802,
    cibil: 738,
    experian: 746,
    crif: 729,
    equifax: 751,
    trend: "up",
    trendPts: 12,
  },
  {
    id: "RPT-20260515",
    pan: "AWPPM4863Q",
    name: "Demo User",
    fetchedAt: "2026-05-15T09:00:00.000Z",
    leapScore: 788,
    cibil: 726,
    experian: 731,
    crif: 718,
    equifax: 740,
    trend: "up",
    trendPts: 8,
  },
  {
    id: "RPT-20260410",
    pan: "AWPPM4863Q",
    name: "Demo User",
    fetchedAt: "2026-04-10T14:15:00.000Z",
    leapScore: 776,
    cibil: 718,
    experian: 723,
    crif: 711,
    equifax: 729,
    trend: "same",
    trendPts: 0,
  },
];

function fmt(iso: string) {
  return new Date(iso).toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

function TrendIcon({ trend, pts }: { trend: ReportEntry["trend"]; pts: number }) {
  if (trend === "up")
    return (
      <span className="flex items-center gap-1 text-body-sm font-medium text-green-600">
        <TrendingUp size={14} /> +{pts} pts
      </span>
    );
  if (trend === "down")
    return (
      <span className="flex items-center gap-1 text-body-sm font-medium text-red-500">
        <TrendingDown size={14} /> {pts} pts
      </span>
    );
  return (
    <span className="flex items-center gap-1 text-body-sm text-foreground-tertiary">
      <Minus size={14} /> No change
    </span>
  );
}

function downloadReport(report: ReportEntry) {
  const lines = [
    `LeapMoney Credit Report — ${report.id}`,
    `Fetched: ${fmt(report.fetchedAt)}`,
    `Name: ${report.name}`,
    `PAN: ${report.pan}`,
    ``,
    `SCORES`,
    `LeapScore™: ${report.leapScore} / 900`,
    `CIBIL:      ${report.cibil} / 900`,
    `Experian:   ${report.experian} / 900`,
    `CRIF:       ${report.crif} / 900`,
    `Equifax:    ${report.equifax} / 900`,
    ``,
    `This is a soft-check report. No impact on your credit score.`,
    `Generated by LeapMoney — leapmoney.net`,
  ].join("\n");

  const blob = new Blob([lines], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${report.id}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export default function CreditReportHistoryPage() {
  const latest = MOCK_REPORTS[0];

  return (
    <div className="mx-auto flex max-w-content flex-col gap-8">
      {/* Header */}
      <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <Heading level={1} size="display-large" className="mb-1">
            Your credit reports
          </Heading>
          <Paragraph color="secondary">
            Soft-check history — no impact on your score. Fetched across all 4 bureaus.
          </Paragraph>
        </div>
        <Link
          href="/credit-report/start"
          className="inline-flex shrink-0 items-center gap-2 rounded-lg bg-interactive-primary px-4 py-2.5 text-body-sm font-semibold text-foreground-on-dark hover:bg-interactive-hover"
        >
          <RefreshCw size={15} /> Fetch fresh report
        </Link>
      </div>

      {/* Latest score summary */}
      <Card className="flex flex-col gap-4 p-5">
        <div className="flex items-center gap-2">
          <CheckCircle size={16} className="text-green-500" />
          <span className="text-label-caps uppercase tracking-wider text-foreground-tertiary">
            Latest report · {fmt(latest.fetchedAt)}
          </span>
        </div>
        <div className="grid grid-cols-2 gap-4 sm:grid-cols-5">
          <div className="col-span-2 sm:col-span-1">
            <p className="text-label-caps uppercase tracking-wider text-foreground-tertiary">LeapScore™</p>
            <p className="text-display font-bold text-interactive-primary">{latest.leapScore}</p>
            <TrendIcon trend={latest.trend} pts={latest.trendPts} />
          </div>
          {(["cibil", "experian", "crif", "equifax"] as const).map((b) => (
            <div key={b}>
              <p className="text-label-caps uppercase tracking-wider text-foreground-tertiary">{b}</p>
              <p className="text-h2 font-bold text-foreground-primary">{latest[b]}</p>
              <p className="text-body-sm text-foreground-tertiary">/ 900</p>
            </div>
          ))}
        </div>
        <div className="flex gap-3">
          <Link
            href={`/credit-report/report?pan=${latest.pan}`}
            className="inline-flex items-center gap-1.5 rounded-lg border border-interactive-primary px-4 py-2 text-body-sm font-medium text-interactive-primary hover:bg-background-page"
          >
            View full report <ChevronRight size={14} />
          </Link>
          <button
            onClick={() => downloadReport(latest)}
            className="inline-flex items-center gap-1.5 rounded-lg border border-border-token-default px-4 py-2 text-body-sm font-medium text-foreground-secondary hover:bg-background-page"
          >
            <Download size={14} /> Download
          </button>
        </div>
      </Card>

      {/* History list */}
      <div>
        <h2 className="mb-3 text-label-caps uppercase tracking-wider text-foreground-tertiary">
          Report history
        </h2>
        <div className="flex flex-col gap-3">
          {MOCK_REPORTS.map((r, i) => (
            <div
              key={r.id}
              className="flex flex-col gap-3 rounded-lg border border-border-token-default bg-background-card p-4 shadow-1 sm:flex-row sm:items-center sm:justify-between"
            >
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-background-page">
                  <FileText size={18} className="text-foreground-tertiary" />
                </div>
                <div>
                  <p className="text-body-md font-medium text-foreground-primary">
                    {fmt(r.fetchedAt)}
                    {i === 0 && (
                      <span className="ml-2 rounded-full bg-interactive-primary/10 px-2 py-0.5 text-label-caps text-interactive-primary">
                        Latest
                      </span>
                    )}
                  </p>
                  <p className="text-body-sm text-foreground-tertiary">
                    LeapScore™ {r.leapScore} · CIBIL {r.cibil} · Experian {r.experian}
                  </p>
                </div>
              </div>
              <div className="flex shrink-0 items-center gap-2">
                <TrendIcon trend={r.trend} pts={r.trendPts} />
                <Link
                  href={`/credit-report/report?pan=${r.pan}`}
                  className="inline-flex items-center gap-1 rounded-md border border-border-token-default px-3 py-1.5 text-body-sm font-medium text-foreground-secondary hover:bg-background-page hover:text-foreground-primary"
                >
                  View <ChevronRight size={13} />
                </Link>
                <button
                  onClick={() => downloadReport(r)}
                  className="inline-flex items-center gap-1 rounded-md border border-border-token-default px-3 py-1.5 text-body-sm font-medium text-foreground-secondary hover:bg-background-page hover:text-foreground-primary"
                >
                  <Download size={13} /> Download
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>

      <p className="text-body-sm text-foreground-tertiary">
        Reports are stored for 12 months. Soft checks are not visible to lenders and do not affect your credit score.
      </p>
    </div>
  );
}
